en/browser-object-model-bom/navigator.md
fixed typo in code 
what's fixed:
typo: navigator.patform
fix: navigator.platform
=> fixed typo navigator.md

tr/Copyright.md, tr/Dedication.md, tr/Preface.md, tr/README.md, tr/References.md, tr/arrays/README.md, tr/arrays/for-each.md, tr/arrays/indices.md, tr/arrays/join.md, tr/arrays/length.md, tr/arrays/map.md, tr/arrays/pop.md, tr/arrays/push.md, tr/arrays/shift.md, tr/arrays/sort.md, tr/arrays/spread.md, tr/arrays/unshift.md, tr/basics/README.md, tr/basics/comments.md, tr/basics/equality.md, tr/basics/types.md, tr/basics/variables.md, tr/json.md
Updated the arrays and readme files for the pagination section. Also translated basics part.
=> Added Basics and updated existing documents with pagination.

en/SUMMARY.md, en/api-ajax.md
Add Web API and AJAX chapter with the explanation and examples.
Fixes:#30
=> API AJAX chapter

en/ECMA-script.md, en/SUMMARY.md
Add ECMA script chapter.
FIXES:#47
=> Ecma script Chapter

en/error-handling/README.md
As mentioned in the issue #65 , I have updated the readme file with proper explanation of error handling in java script.
have a look and merge my pull request @sumn2u
=> Readme file for Error Handling 

en/interview-questions/basic-level.md
=> interview-questions/basic-level

en/numbers/math.md
=> Solved #81 issue

en/conditional/nested-if-else.md
Creates a nested-if-else conditional with explanation and programs. 
Fixes issue #84
=> [feat]: Create a nested-if-else explannation and examples issue #84

en/List_of_learning_resources.md
Hello @sumn2u I have added the files. Can you please review it?
=> added a list of learning resources for JavaScript

en/exercises/concatenation.md, en/exercises/conditional-statements.md, en/exercises/constants.md, en/exercises/fizzbuzz-problem.md, en/exercises/functions.md, en/exercises/multiplication.md
Exercise are added for concatentation, conditional statements, constants and functions.
=> DOCS: Adding some new exercise

en/numbers/operators.md
This pull request address issue #82
=> DOCS: Updated Operator.md with explanation of new operators

en/design-patterns/README.md, en/design-patterns/behavioral-patterns.md, en/design-patterns/creational-patterns.md, en/design-patterns/structural-patterns.md
This PR fix the typo in files present inside `design-patterns/` folder
=> Chore: Typos fixed in  design_patterns folder

en/miscellaneous/Added getters and setters.md
Hello @sumn2u I have added getters and setters in miscellaneous section. Please review this PR and add hacktoberfest tag too.
Thank you.
=> Added getters and setters

en/es6-concepts/Maps.md
Hello @sumn2u I have added JavaScript Maps in ES6 section. Please review this PR and add hacktoberfest tag too.
Thank you.
=> Added JavaScript Maps 

en/interview-questions/advance-level.md
Hello @sumn2u I have added questions in advance level interview questions section. Please review this PR and add hacktoberfest tag too.
Thank you.
=> Added questions in advance level

en/FileSystem/filesystem.md
Read and Write from the file synchronously and asynchronously
=>  added filesystem , asynchronous and non blocking i/o

README.md
I have added a new table of contents section that can be used to directly go to a particular section by clicking on the particular link .
I merged the edit section and contribution sectoin and made a new section -- contributing guidelines , beacuse the previous one had repeated lines,it seems much clear now . 
I changed some basic tags, highlighted some main sentences .added some new lines to contributors section and did some other minor grammer corrections
=> Updated Readme.md   ref#130

en/interview-questions/intermediate-level.md
=> Added Interview question

_layouts/website/layout.html
=> fix: Add OG image in metadata

en/interview-questions/advance-level.md
I have added a question describing the `Execution Context` and `Lexical Environment` of a function. Generally, This is an unexpected shoot from interviewers.
Solved #154
=> [ADD] An advanced interview question

en/loops/break.md
I have added the break statement in the loops section in English.
added syntax and two examples with explanation.
=> Added break statement in loops section

en/browser-object-model-bom/cookies.md
=> fixed a small typo

en/README.md
=> Bug: Navigation Links Not Highlighting on Scroll Down #152

en/interview-questions/advance-level.md
I have added a questions on Code Optimization under tree shaking concept . Generally, This is an unexpected shoot from interviewers.
Solved #154
=> [ADD] An Advance interview question

en/arrays/length.md
Fixes layout design on arrays length chapter.
=> fix: layout fixes of arrays length chapter

en/interview-questions/basic-level.md
Add one basic level question on Json concept
solved #69
=> JavaScript Interview Questions [ Updated: Basic Level ] 

en/functions/set-interval.md, en/functions/set-timeout.md
I completed writing the documents for `setTimeout()` and `setInterval()` (sorry for the wait). They will be under the [function](https://javascript.sumankunwar.com.np/en/functions/) section and I made sure to add examples of what they do as well.
If there's any mistake I made or things I should've done, please let me know or assign someone to fix that mistake.
=> Set timeout and set interval documents

en/miscellaneous/ECMA-script.md
I have added the most used functions syntaxes issue solved #184
=> Examples Added of ES6 Syntax

en/complexity/README.md
This MR aims to solve issue https://github.com/sumn2u/learn-javascript/issues/112
Considering space and time complexity is a significant aspect of programming that ensures code efficiency, scalability, and maintainability. Having a brief introduction to these concepts, followed by example, can greatly benefit JavaScript developers.
=> Write space and time complexity chapter

package.json
The scroll up issue that occurs while navigating sidebar contents is fixed.
https://github.com/user-attachments/assets/3eefd660-7a50-4397-b158-08e9c549e7c5
Fixes #223
=> fix scroll up issue on sidebar

es/Credits.md
Added translated by section in Spanish translation.
=> add translated by section in credits.md

en/complexity/README.md, en/complexity/space-complexity.md, en/complexity/time-complexity.md
=> Added content in time complexity and space complexity sections.

package.json
=> Fixing Non-Responsive Content in Interview Section

en/SUMMARY.md, en/error-handling/README.md, en/error-handling/async_errorhandling.md
=> add asynchronous chapter to error handling

en/SUMMARY.md, en/behind-scenes/README.md, en/behind-scenes/call-stack.md, en/behind-scenes/engine.md, en/behind-scenes/event-loop.md, en/behind-scenes/execution-context.md, en/behind-scenes/memory-heap.md, en/behind-scenes/runtime-environment.md
=> restructure javascript behind the scenes chapter

de/file-system/README.md
Translated everything as-is and cleaned up the issues.
=> Add German translation README.md
