en/loops/for.md
=> DOCS: Added for for of loop in js

en/regular-expression.md
=> updated /en/regular-expression.html

en/interview-questions/intermediate-level.md
I have added a question describing the truthy and falsy values in javascript. Generally, This is an unexpected shoot from interviewers.
Solved https://github.com/sumn2u/learn-javascript/issues/154
=> [ADD] An intermediate interview question

.github/workflows/create_issue_on_en_changes.yml
My solution uses the power of workflows to trigger an event after each change on the english version to get the diffs on the english version that have been changed. If changes have been made, then an issue is created for it !
References enhancement proposed in #131
=> Adding the way to issue maintainers the need for translation

web-apis.md
This pull request adds a new section titled "Web APIs" to the Learn JavaScript project. This section covers various Web APIs that are essential for modern JavaScript development.
- Added a new section in the table of contents.
- Created subsections for DOM Manipulation, Fetch API, Geolocation API, Canvas API, Storage API, and Notification API.
- Included practical code examples for each Web API.
- Provides practical examples of using Web APIs.
- Enhances learners' understanding of how to interact with the browser and web server.
- Makes the curriculum more comprehensive and up-to-date with current JavaScript practices.
I look forward to feedback and suggestions. Thank you for reviewing my contribution.
=> Add Web APIs section with examples

en/interview-questions/intermediate-level.md
A new section for the interview questions about ES6 classes, Key topics are Class Members, Access Modifiers, Class Properties, Constructors, and Static vs Instance Members. 
At least some knowledge of Object-oriented Programming is required to answer these questions effectively.
=> Add "Classes" section to intermediate interview questions

book.json, en/exercises/concatenation.md, en/exercises/conditional-statements.md, en/exercises/console.md, en/exercises/constants.md, en/exercises/fizzbuzz-problem.md, en/exercises/functions.md, en/exercises/get-the-titles.md, en/exercises/multiplication.md, en/exercises/objects.md, en/exercises/user-input-variables.md, package.json
Support javascript interpreter on web browser
=> support javascript interpreter

en/classes/composition.md
Add a section about class composition
=> Class-updates

en/interview-questions/basic-level.md
=> added hyperlinks to eachscope

en/error-handling/async_errorhandling.md
this pr is based on the issue #243
=> added about error handling for async english

en/document-object-model/README.md, en/document-object-model/dom-api.md, en/document-object-model/dom-manipulation.md, en/document-object-model/listening-of-events.md, en/resources.md
Fixes #263 
Please review my PR @sumn2u and add the `hacktoberfest-accepted` label to it
=> New chapter on DOM added

en/miscellaneous/debugging.md
Expanded The console.log() section
Added Using Breakpoints section
Restructured Key Panels in Developer tools bullet points Added Watch Expressions and Scope section
Added Stack Trace and Call Stack section
Added Common Debugging Strategies section
=> Update debugging.md [Issue #28]

en/basics/comments.md
This pull request addresses issue #79  by restructuring the `comments.md` file in the English content directory.
- Applied the section layout suggested in the issue:
- Added `## Types of Comments` with `### Single Line` and `### Multi Line` subsections.
- Added a new section: `## Real life examples of comments` with sample DOM manipulation code.
- Improved paragraph structure for better readability.
- Preserved original explanations and examples while enhancing clarity and formatting.
Let me know if any adjustments are needed. Happy to iterate!
Closes #79
=> Restructure comments.md with suggested format (#79)

_layouts/website/languages.html
- Update landing page to clean design 
- Add some Icons
=> issue #244 - Update landing page design 

de/arrays/slice.md
Created a new file in de/array, based on en/array 
reviewed the content
=> feat(arrays): German add slice.md

en/regular-expression.md
=> fix: Fix syntax errors in regular-expression.md (#290)

en/complexity/space-complexity.md
=> fixes[#310] Update space complexity chapter formatting (remove $)

en/beginner-projects/digital-clock.md, en/beginner-projects/electronic-drum-kit.md, en/beginner-projects/image-search.md, en/beginner-projects/monthly-calendar.md, en/beginner-projects/random-photos-generator.md, en/beginner-projects/rock-paper-scissors-game.md, en/beginner-projects/simple-stopwatch.md, en/beginner-projects/tip-calculator.md, en/beginner-projects/video-trailer-popup.md, en/beginner-projects/weather-app.md
I have made changes in project files. Convert png to PNG.
=> Fix preview images

examples/video-popup/README.md, examples/video-popup/index.html, examples/video-popup/script.js, examples/video-popup/style.css
Below concepts used in the Example:
Modal: A container overlaying the page for focused content
Event Listeners: Detects clicks or key presses
Video Control: Using .play(), .pause(), .current Time to manage playback
CSS Overlay: Covers the page for modal background
Responsive Design: Adapts layout to fit different devices
=> #326: Solution for a Video Popup Modal

en/beginner-projects/video-trailer-popup.md
Demo application of video trailer popup example
=> added video trailer popup model

examples/Drum_kit/README.md, examples/Drum_kit/index.html, examples/Drum_kit/script.js, examples/Drum_kit/styles.css
Issue #319 
Interactive Drum Kit Using Html, CSS, and JS 
https://github.com/user-attachments/assets/8e0a8063-0116-48ef-b1ee-3d5f70f62335
=> Interactive-Drum-Kit

examples/Rock-Paper-Scissors/README.md, examples/Rock-Paper-Scissors/index.html, examples/Rock-Paper-Scissors/script.js, examples/Rock-Paper-Scissors/styles.css
Added a complete **Rock-Paper-Scissors** game example in the `examples/` folder demonstrating DOM manipulation, event handling, animations, and game logic with score tracking.
- ✊🖐️✌️ Buttons for Rock, Paper, and Scissors  
- 🤖 Random computer moves  
- 🧮 Real-time score tracking (User vs Computer)  
- ⚡ Winner determination per round  
- 🎞️ Smooth animations and visual feedback  
- 🔊 Optional sound effects for actions  
- 🔁 Reset button to restart the game  
- 🕹️ Round history showing past moves and results  
- `index.html` — Game UI structure with buttons and score display  
- `styles.css` — Responsive, animated design for better UX  
- `script.js` — Core game logic with event handling, animations, and scoring  
- `README.md` — Game overview and setup instructions  
DOM Manipulation • …
=> Create an Example Solution for a Rock Paper Scissors Game #323

en/beginner-projects/image-search.md
Image search demo application added
=> added image search app
